name: Australia 2015
favicon: null
layout_spectrum: 0.8268
typography_spectrum: 0.37515
title: December 2015 in Australia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7faad4'
    - '#304f64'
    - '#0a0d16'
    - '#fefefc'
    - '#ff6448'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
