name: Australia 2015
favicon: null
layout_spectrum: 0.88182
typography_spectrum: 0.37515
title: December 2015 in Australia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7ba7ce'
    - '#19231a'
    - '#ffe538'
    - '#cd9e2d'
    - '#d21d29'
  brandStrength: 1
  lightness: 0.3972763125784695
  saturation: 0.19827494653873146
  rhythmicContrast: 0.14790526661090553
purpose: []
